n_classes: 2
split_dir: ${data_dir}/splits
unity_dir: ${data_dir}/flows/flow_unity_step_pth
raft_dir: ${data_dir}/flows/flow_raft_step_pth
masked: false
n_temporal_mask: 1
spatial_mask_size: 20
flow_type: "positive"