n_classes: 2
split_dir: ${data_dir}/splits
unity_dir: ${data_dir}/flow_unity_unit_pth
raft_dir: ${data_dir}/flow_raft_unit_pth
check_dir: ${hydra:run.dir}/check
masked: false
n_temporal_mask: 1
spatial_mask_size: 20