stride: 16
n_frames: 16
split_dir: ${data_dir}/splits
bbox_dir: ${data_dir}/detections/tracked_detections
flow_dir: ${data_dir}/flows/flow_raft_unit_pth
frame_dir: ${data_dir}/raw_cm/raw_frames/
check_dir: ${hydra:run.dir}/check