program: flow_encoder/run.py

method: bayes

metric:
  goal: minimize
  name: val/raw_loss

parameters:
  run_type:
    value: train
  project_name:
    value: camera-style-sweep
  xp_name:
    value: vqvae
  data_dir:
    value: /media/hdd_robin/Unity_224_motion
  compnode.batch_size:
    value: 32
  model.margin:
    value: 1.0

  model.grad_norm_alpha:
    distribution: uniform
    min: 0.1
    max: 0.4
  model.learning_rate:
    distribution: uniform
    min: 0.0001
    max: 0.01
  model.contrastive_mode:
    values: ["triplet", "ranking"]
  model.n_embeddings:
    values: [32, 64, 128]
  model.commitment_cost:
    distribution: uniform
    min: 0.6
    max: 1.0


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
