module_name: triplet_i3d

pretrained_path: ${model_dir}/flow_imagenet.pt
checkpoint: null
optimizer: sgd
softmax: false
learning_rate: 5e-3
weight_decay: 1e-4
momentum: 0.9

freeze: false

n_frames: 16
frame_size: 224
unity_mod_max: 26
raft_mod_max: 69
