module_name: autoencoder_i3d

histogram: false
grid_dims: [6, 10]
n_angle_bins: 8

model_size: small
pretrained_path: null
checkpoint_path: ${checkpoint_dirpath}/autoencoder_last.ckpt
triplet_coef: 0.5
reconstruction_coef: 1
optimizer: adam
softmax: false
learning_rate: 1e-3
weight_decay: 1e-4
momentum: 0.9
margin: 1.0

n_frames: 16
stride: 16
frame_size: 224
