module_name: contrastive_encoder_i3d

histogram: false
grid_dims: [6, 10]
n_angle_bins: 8

model_size: small
pretrained_path: ${model_dir}/flow_imagenet.pt
checkpoint_path: ${checkpoint_dirpath}/encoder_last.ckpt
optimizer: adam
softmax: false
learning_rate: 1e-3
weight_decay: 1e-4
momentum: 0.9
margin: 1.0

n_frames: 16
stride: 16
frame_size: 224
