module_name: contrastive_autoencoder_i3d

model_size: small
pretrained_path: null
checkpoint_path: ${checkpoint_dirpath}/contrastive_autoencoder_last.ckpt
optimizer: adam
softmax: false
learning_rate: 1e-2
weight_decay: 1e-4
momentum: 0.9
contrastive_mode: ranking
margin: 1.0
grad_norm_alpha: 0.5

n_frames: 16
stride: 16
frame_size: 224
