module_name: contrastive_vqvae_i3d

histogram: false
model_size: small
pretrained_path: null
checkpoint_path: ${checkpoint_dirpath}/contrastive_vqvae_last.ckpt
optimizer: adam
softmax: false
learning_rate: 1e-3
weight_decay: 1e-4
momentum: 0.9
contrastive_mode: ranking
margin: 1.0
grad_norm_alpha: 0.1
n_embeddings: 256
commitment_cost: 0.25
early_stopping_patience: null

n_frames: 16
stride: 16
frame_size: 224
