module_name: contrastive_autoencoder_i3d

histogram: false
pretrained_path: null
checkpoint_path: ${checkpoint_dirpath}/contrastive_autoencoder_last.ckpt
triplet_coef: 0.5
reconstruction_coef: 1
optimizer: adam
softmax: false
learning_rate: 1e-3
weight_decay: 1e-4
momentum: 0.9

n_frames: 16
stride: 16
frame_size: 224
unity_mod_max: 0.14
raft_mod_max: 165.53
