module_name: encoder_i3d

histogram: false
pretrained_path: ${model_dir}/flow_imagenet.pt
checkpoint_path: ${checkpoint_dirpath}/encoder_last.ckpt
optimizer: adam
softmax: false
learning_rate: 1e-3
weight_decay: 1e-4
momentum: 0.9

n_frames: 16
stride: 16
frame_size: 224
