defaults:
  - _self_
  - compnode: light_1n_1g_28b.yaml
  - model: encoder_i3d.yaml
  - datamodule: unit_flow.yaml

num_epochs: 51

# Type of run to launch (current: train, TODO: debug/eval/infer/...)
run_type: train

root: ${hydra:runtime.cwd}
# Path to folder with data
data_dir: ${data_dir}
# Path to folder for testing (junk folder)
test_dir: ${root}/flow_encoder/tests
# Path to folder with pre-trained models
model_dir: ${root}/flow_encoder/models
result_dir: ${root}/flow_encoder/results
viz_dir: ${root}/visualizations

# Name of the project is accessed by loggers
project_name: camera-style-flow-encoder
# Name of the run is accessed by loggers
xp_name: null
# Wether to synced the logs or not (WandB)
log_offline: false
# Metric to monitor to save models
checkpoint_metric: "val/loss"
# Directory to save model checkpoints
checkpoint_dirpath: ${root}/flow_encoder/checkpoints

# Seed for random number generators
seed: 1
# Pretty print config at the start of the run using Rich library
print_config: True
# Disable (or not) python warnings
ignore_warnings: True

hydra:
  run:
    dir: ${hydra:runtime.cwd}/flow_encoder/outputs/${now:%Y-%m-%d}/${xp_name}-${now:%H-%M-%S}